title: Resume
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# about section

fname: Deepak
lname: Raj
email: deepak008@live.com
mobile: +91- 9818183049
address: New Delhi
linkedin_username: deepak-raj-35887386
dev_username: codeperfectplus
github_username:  codeperfectplus
facebook_username: mrperfect9015
about_me: >- # this means to ignore newlines until "baseurl:"
  Dedicated, passionate, and competent for new technology with experience in Python, Machine learning, and Computer vision.
  capable of thinking out-of-the-box to create seamless, exciting products for the target audience. Excellent analytical 
  thinking and written/verbal communication skills.

# Build settings
theme: minima
plugins:
  - jekyll-feed
